#pragma once

enum class FlagType {
	INCREASE_FOOD,
	DECREASE_FOOD,
	INCREASE_WOOD,
	DECREASE_WOOD,
	INCREASE_IRON,
	DECREASE_IRON,
	INCREASE_HOUSE,
	INCREASE_CITIZEN,
	DECREASE_CITIZEN,
	INCREASE_SPACE,
	DECREASE_SPACE,
	END_SEARCH,
};